name: '📚 ドキュメント（Documentation）'
description: 'ドキュメントに関する修正・改善依頼'
title: '[Documentation]: '
labels: ['documentation']
body:
  - type: markdown
    attributes:
      value: |
        ドキュメントに関する修正・改善依頼
  - type: textarea
    id: 01-about
    attributes:
      label: '概要'
      description: |
        Add a description
      placeholder: 'markdown形式で記述してください'
    validations:
      required: true
