name: lint

on:
  pull_request:

jobs:
  format:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: swift-format version
        run: swift format --version
      - name: Lint
        run: swift format lint --strict --recursive Sources Tests
